- type: job
  id: TaipanAtmosTech
  name: job-name-taipan-atmos-tech
  playTimeTracker: TaipanAtmosTech
  description: Атмосферный инженер из далёкого космоса.
  startingGear: SyndicateAtmos
  icon: "JobIconSyndicateAtmos"
  supervisors: job-supervisors-taipan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 54000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess

- type: startingGear
  id: SyndicateAtmos
  equipment:
    ears: ClothingHeadsetAltTaipan
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndie
    shoes: ClothingShoesBootsTaipan
    back: ClothingBackpackSyndicate
    belt: ClothingBeltAssaultTaipan
    id: SyndiPDAEng
