- type: job
  id: TaipanBotanist
  name: job-name-taipan-botanist
  playTimeTracker: TaipanBotanist
  description: Ботаник из далёкого космоса.
  startingGear: SyndicateBotanist
  icon: "JobIconTaipanBotanist"
  supervisors: job-supervisors-taipan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 6000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess

- type: startingGear
  id: SyndicateBotanist
  equipment:
    ears: ClothingHeadsetAltTaipan
    jumpsuit: ClothingUniformJumpsuitTaipanBotanist
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesColorBlack
    id: SyndiPDABotan
