- type: job
  id: TaipanCargotech
  name: job-name-taipan-cargotech
  playTimeTracker: TaipanCargotech
  description: Карготехник из далёкого космоса.
  startingGear: SyndicateCargotech
  icon: "JobIconTaipanCargotech"
  supervisors: job-supervisors-taipan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 18000
    - !type:OverallPlaytimeRequirement
      time: 36000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess

- type: startingGear
  id: SyndicateCargotech
  equipment:
    ears: ClothingHeadsetAltTaipan
    jumpsuit: ClothingUniformJumpsuitTaipanCargotech
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesBootsCombatSyndie
    id: SyndiPDACargo
