- type: job
  id: TaipanMedic
  name: job-name-taipan-medic
  playTimeTracker: TaipanMedic
  description: Медик из далёкого космоса.
  startingGear: SyndicateParamedic
  icon: "JobIconSyndicateParamedic"
  supervisors: job-supervisors-taipan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 6000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess

- type: startingGear
  id: SyndicateParamedic
  equipment:
    eyes: ClothingEyesHudSyndicateAgentTaipan
    ears: ClothingHeadsetAltTaipan
    jumpsuit: ClothingUniformJumpsuitParamedicSyndie
    outerClothing: ClothingOuterMedTaipan
    shoes: ClothingShoesBootsCombat
    id: MedicalPDASyndi
    back: ClothingBackpackSyndicate
    belt: ClothingBeltMedicalFilled
