- type: job
  id: TaipanScience
  name: job-name-taipan-science
  playTimeTracker: TaipanScience
  description: Учёный из далёкого космоса.
  startingGear: SyndicateScience
  icon: "JobIconSyndicateScience"
  supervisors: job-supervisors-taipan-rd
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 6000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess

- type: startingGear
  id: SyndicateScience
  equipment:
    ears: ClothingHeadsetAltTaipan
    jumpsuit: ClothingUniformScienceTaipan
    outerClothing: ClothingOuterCoatLabOpened
    gloves: ClothingHandsScienceTaipan
    shoes: ClothingShoesBootsCombat
    back: ClothingBackpackSyndicate
    id: SyndiPDAScience
