- type: job
  id: TaipanTelecommunicationsOfficer
  name: job-name-taipan-telecommunications-officer
  playTimeTracker: TaipanTelecommunicationsOfficer
  description: Офицер телекоммуникаций из далёкого космоса.
  startingGear: SyndicateFormal
  icon: "JobIconSyndicateFormal"
  supervisors: job-supervisors-taipan-syndicate
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 60000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 60000
    - !type:DepartmentTimeRequirement
      department: Command
      time: 108000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000
    - !type:OverallPlaytimeRequirement
      time: 360000
    - !type:AgeRequirement
      requiredAge: 26
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess

- type: startingGear
  id: SyndicateFormal
  equipment:
    eyes: ClothingEyesHudTaipan
    ears: ClothingHeadsetAltTaipan
    shoes: ClothingShoesBootsCombat
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    gloves: ClothingHandsGlovesCombat
    id: SyndiPDACom
    back: ClothingBackpackSyndicate
    belt: ClothingBeltAssaultTaipan
    pocket1: SyndicateWhistle
    pocket2: ClothingMaskGasSyndicate
