- type: department
  id: Taipan
  name: department-Taipan
  description: department-Taipan-description
  color: "#D381C9"
  roles:
  - TaipanAtmosTech
  - TaipanBotanist
  - TaipanCargotech
  - TaipanChef
  - TaipanMedic
  - TaipanRD
  - TaipanScience
  - TaipanTelecommunicationsOfficer
